export const initialAssociateState = {
    nome: '',
    user: '',
    senha: '',
    cargo: '',
    nacionalidade: '',
    cpf: '',
    nascimento: new Date(),
    naturalidade: '',
    sexo: '',
    estadoCivil: '',
    conjuge: '',
    nascimentoConjuge: new Date(),
    filhos: '',
    cep: '',
    endereco: '',
    numero: '',
    complemento: '',
    bairro: '',
    cidade: '',
    estado: '',
    lotacao: '',
    atuacao: '',
    cepFuncional: '',
    enderecoFuncional: '',
    numeroFuncional: '',
    complementoFuncional: '',
    bairroFuncional: '',
    cidadeFuncional: '',
    estadoFuncional: '',
    telefone: '',
    fax: '',
    celular: '',
    email: '',
    emailListaRejufe: '',
    emailListaAscom: '',
    admissao: new Date(),
  }